version: 2
jobs:
  build:
    working_directory: /home/koa-single-page
    docker:
      - image: node:8

    steps:
      - checkout

      - setup_remote_docker

      - restore_cache:
          key: koa-single-page-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Dependencies
          command: sh script/setup

      - run:
         name: Lint
         command: sh script/lint

      - run:
          name: Test
          command: sh script/test

      - run:
          name: Build
          command: sh script/build

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.04.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: List After
          command: ls -la

      - save_cache:
          key: koa-single-page-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - /tmp/docker

      - store_test_results:
          path: junit.xml
